package org.drooms.strategy.tomason.path

import org.slf4j.Logger
import java.util.ArrayList
import java.util.Random

import org.drooms.strategy.tomason.components.collectibles.*
import org.drooms.strategy.tomason.components.collision.*;
import org.drooms.strategy.tomason.components.history.*
import org.drooms.strategy.tomason.components.status.*
import org.drooms.strategy.tomason.components.*

import org.drooms.api.*
import org.drooms.impl.logic.*
import org.drooms.impl.logic.facts.*
import org.drooms.impl.logic.events.*

import org.drools.runtime.rule.FactHandle
import org.drools.runtime.rule.WorkingMemoryEntryPoint

global Logger logger
global PathTracker tracker

declare entry-point gameEvents end
declare entry-point rewardEvents end
declare entry-point playerEvents end


rule "Add extra priority to straight moves"
    salience 5
    when
        CurrentTurn($turn : number)
        PastMove(turn == ($turn - 1), move != Move.STAY, $past : move)
        $move : PriorityMove(move == $past)
    then
        modify($move) {
            addPriority(1000)
        }
end

rule "Insert priority move for every collectible"
    when
        Status($position : position)
        $col : PositionedCollectible()
    then
        insertLogical(new PriorityMove($position, $col.getFirstStep(),
            Functions.getPriority($col.getCollectible().getPoints(), $col.getDistance())));
end
