package cz.schlosserovi.tomas.drooms.strategy

import org.slf4j.Logger
import java.util.ArrayList
import java.util.Random

import cz.schlosserovi.tomas.drooms.strategy.domain.*
import cz.schlosserovi.tomas.drooms.strategy.domain.collision.*;
import cz.schlosserovi.tomas.drooms.strategy.domain.history.*
import cz.schlosserovi.tomas.drooms.strategy.domain.status.*
import cz.schlosserovi.tomas.drooms.strategy.domain.*

import org.drooms.api.*
import org.drooms.impl.logic.*
import org.drooms.impl.logic.facts.*
import org.drooms.impl.logic.events.*

global Logger logger
global PathTracker tracker

declare entry-point gameEvents end
declare entry-point rewardEvents end
declare entry-point playerEvents end


rule "Start the clock"
    salience Integer.MAX_VALUE
    when
        CurrentTurn($turn : number)
    then
        insert(new TimeHolder(System.currentTimeMillis(), $turn));
end

rule "Print the time"
    salience Integer.MAX_VALUE
    when
        PastMove($turn : turn)
        $holder : TimeHolder(turn == $turn)
    then
        logger.info("Time for turn {}: {} ms", $turn, $holder.getDelta(System.currentTimeMillis()));
end
